### ISSUE TITLE
[EPIC] Complete Plan

### ISSUE THREAD

**Issue by rufuspollock** [rufuspollock/year-in-the-life#1]
Phase I: MVP

* [x] Explore existing visualization options
* [x] Get something basic working
* [x] Get it working with CSV data
* [x] Parse ics (see local copy) into structured csv (modify csv maybe and load off that)
  * [x] Get this working in the browser
* [x] Use live ics from online (or automate scraping in a script ...)

Phase II:

* [x] Show colors for calendar
* [x] Experiment with different layouts (rather than swim lanes ...)
* [ ] Redesign calendar design to show key info:
  * where we are
  * what we are doing
  * if just one of us ...

Misc

* [ ] Allow user to set time period
* [ ] Show year next to calendar
* [ ] Show name of calendar
* [ ] Allow user to set calendar link

Next steps

* [x] Get this working in the browser ... **got this working against google calendar with an allow CORs plugin**
  * Load local ics file ...
  * parse
  * pass to renderer (instead of loading CSV ...)

**Comment by rufuspollock** [comment]
🚚 MOVED to PLAN.md
